version: 2
jobs:
  build:
    working_directory: ~/repo    
    docker:
      - image: circleci/python:3.8.4-buster
        environment:
          - "DATASHARE_VERSION=7.1.3"
    steps:
      - checkout
      - run:
          name: Build Datashare package name
          command: echo 'export DATASHARE_PACKAGE="datashare-dist_${DATASHARE_VERSION}_all.deb"'  >> $BASH_ENV
      - run:
          name: Download Datashare for Debian
          command: wget "https://github.com/ICIJ/datashare-installer/releases/download/${DATASHARE_VERSION}/${DATASHARE_PACKAGE}"
      - run:
          name: Install Datashare
          command: (sudo apt update || /bin/true) && sudo apt install ./$DATASHARE_PACKAGE
      - run:
          name: Run Datashare in background
          command: datashare
          background: true
      - run:
          name: Wait for Datashare to be up
          shell: /bin/sh
          command: wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8080
      - run:
          name: Install dependencies
          command: |
            sudo apt install pipenv
            make install
      - run:
          name: Run tests
          command: |
            pipenv run nosetests
