version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          - "TEST_ELASTICSEARCH_URL=http://elasticsearch:9200"
          - "TEST_DATASHARE_URL=http://datashare:8080"
      - name: datashare
        image: icij/datashare:4.3.2
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        restart: on-failure
        environment:
          - "http.host=0.0.0.0"
          - "transport.host=0.0.0.0"
          - "cluster.name=datashare"
          - "discovery.type=single-node"
          - "discovery.zen.minimum_master_nodes=1"
          - "xpack.license.self_generated.type=basic"
          - "http.cors.enabled=true"
          - "http.cors.allow-origin=*"
          - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
          - "cluster.routing.allocation.disk.threshold_enabled=true"
          - "cluster.routing.allocation.disk.watermark.flood_stage=5gb"
          - "cluster.routing.allocation.disk.watermark.low=30gb"
          - "cluster.routing.allocation.disk.watermark.high=20gb"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --editable . nose responses

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
