version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8-buster
        environment:
          - "DATASHARE_VERSION=9.0.2"
    steps:
      - checkout
      - run:
          name: Build Datashare package name
          command: echo 'export DATASHARE_PACKAGE="datashare-dist_${DATASHARE_VERSION}_all.deb"'  >> $BASH_ENV
      - run:
          name: Download Datashare for Debian
          command: wget "https://github.com/ICIJ/datashare-installer/releases/download/${DATASHARE_VERSION}/${DATASHARE_PACKAGE}"
      - run:
          name: Install Datashare
          command: (sudo apt update || /bin/true) && sudo apt install ./$DATASHARE_PACKAGE
      - run:
          name: Run Datashare in background
          command: datashare -p test-datashare -u test
          background: true
      - run:
          name: Install Poetry
          command: |
            export TERM=xterm-256color
            export COLUMNS=150
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install Python dependencies
          command: |
            poetry install --with dev
            poetry run pip install matplotlib
      - run:
          name: Wait for Datashare to be up
          shell: /bin/sh
          command: wget --retry-connrefused --waitretry=5 --read-timeout=30 --timeout=30 -t 10 http://localhost:8080
      - run:
          name: Run tests
          command: |
            TEST_ELASTICSEARCH_URL=http://localhost:9200 make test
